version: '3.8'

services:
  db:
    image: postgres:15
    container_name: educourses-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: educourses
    ports:
      - "5434:5432"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: educourses
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
